### PR TITLE
Fix #1

### LINKED ISSUE #1: useEffect executes many times during render when using options
when using the second parameter, the `useEffect` gets called many times, leading to multiple calls to onChange, and multiple location changes, even if they aren't happening. either put on the readme that you need to pass an `useMemo`'ed options object or useMemo inside the hook

### PR DESCRIPTION
**Pull request by mewben**
this prevents useEffect from running endlessly.

### CODE REVIEW

**Comment by trekhleb** [comment]
Thanks for the PR @mewben!

**Comment by techieeliot** [comment]
# Hey 👋 

@mewben 

I'm having this type of usePosition() issue in my react app component. I have the most up to date version, so maybe I'm totally misusing this hook, but I'm not sure how to reduce the number of times that useEffect will call to the API.

# Component Snippet
``` javascript 
import { usePosition } from 'use-position';
import axios from 'axios';
import UseCurrentPosition from './UseCurrentPosition';
    
const LocalForecast = (props) => {
    const watch = true;
    const { latitude, longitude } =  usePosition(watch, {enableHighAccuracy: true, maximumAge: 300});
    const [ weather, setWeather ] = useState([])
   
    const location = {
       'latitude': `${latitude}`, 
       'longitude': `${longitude}`
    }

    useEffect( () => {
        if(latitude){
            axios.get('http://localhost:8080', {
                params: {
                    lat: latitude, 
                    lon: longitude
                }
            })
            .then((response) => response.data)
            .then((data) => setWeather(data))
            .catch(err => console.log(err));
            console.log(weather)
        }
    }, [location])
```

# console.log repetitions of weather data

Screen Shot 2020-05-13 at 4 43 05 PM

## Thanks 🙌

**Comment by mewben** [comment]
`watch: boolean - set it to true to follow the location.`

Hi @techieeliot I believe watch=true constantly tracks your location therefore throwing you new values everytime. If you're not interested to follow location changes, try watch=false. :) Hope this helps :)

**Comment by techieeliot** [comment]
Hey @mewben, 
Thanks for explaining. That change did the trick.

**Pull request merged**
